### ISSUE TITLE
Not compatible with the version of your running IDE (PhpStorm 2024.1)

### ISSUE THREAD

**Issue by CrazyBoy49z** [BJWielink/LabelTranslate#3]
Not compatible with the version of your running IDE (PhpStorm 2024.1)

**Comment by BJWielink** [comment]
I am working on a new version that should fix a whole lot of issues. Most notably:

- Hierarchical translations support
- Bug fix where translations folders get mixed up
- No more manual saving and refreshing because I'll be listening to VFS events that allow me to automatically keep the file and translation UI in sync
- Smarter way of finding translation folders, also supporting the newer Laravel translation standard.

The current code base is really messy because, as the description states, it was rushed. For this reason the changes mentioned above will unfortunately become part of a rewrite from scratch. This means that the ETA is about 2 weeks for the new version.

I don't plan to support / update this old version, because it is a chore to work with the current code base.
